# Generated by Django 2.1.7 on 2019-10-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=500)),
                ('platform', models.CharField(max_length=100)),
                ('expire_at', models.TextField()),
            ],
        ),
    ]
